framework:
  notifier:
    chatter_transports:
      firebase: '%env(FIREBASE_DSN)%' # DSN Firebase pour le transport des messages
    texter_transports:
      sms: '%env(TWILIO_DSN)%'  # Transport SMS (exemple avec Twilio)
    channel_policy:
      urgent: ['email', 'sms']
      high: ['email', 'sms']
      medium: ['email']
      low: ['email']
    admin_recipients:
      - { email: 'admin@example.com' }
