security:
  password_hashers:
    App\Entity\Utilisateur:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        check_path: /login
        username_parameter: email
        password_parameter: password
        success_handler: App\Security\LoginSuccessHandler
        failure_handler: App\Security\LoginFailureHandler
      logout:
        path: /logout
        target: /

  access_control:
    - { path: ^/admin, roles:  }
    - { path: ^/register, roles: }
    - { path: ^/login, roles:  }
